# Generated by Django 5.1 on 2026-04-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawprice",
            name="url",
            field=models.URLField(max_length=2000),
        ),
    ]
