# Generated by Django 5.1 on 2026-04-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_alter_rawprice_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawprice",
            name="image_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
